name: Test

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.16'

      - name: Setup pip
        run: |
          pip install --upgrade pip
          pip install numpy --upgrade
          # pip install numpy --no-cache-dir
          pip install scipy
          pip install matplotlib
          pip install msgpack-rpc-python
          # pip install airsim==1.8.1

      - name: Setup airsim
        run: |
          pip install airsim==1.8.1

      - name: Hello World
        run: |
          python test.py
