name: Test

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    # runs-on: [self-hosted, Linux, gpu]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup pip
        run: |
          python3 -m pip install --upgrade pip
          pip install numpy --upgrade
          pip install scipy
          pip install matplotlib
          pip install msgpack-rpc-python
          pip install airsim==1.7.0